# Adapted from: https://github.com/james-willett/mkdocs-material-youtube-tutorial

site_name: Cameron Candau
site_url: https://cameroncandau.com
theme:
  logo: images/favicon.png
  favicon: images/favicon.png
  name: material
  features:
    #- navigation.tabs
    #- navigation.sections
    #- toc.integrate
    #- navigation.top
    #- search.suggest
    #- search.highlight
    #- content.tabs.link
    #- navigation.instant
    #- content.code.annotation
    #- content.code.copy
  language: en
  palette:
    - scheme: slate 
      #toggle:
      #  icon: material/toggle-switch
      #  name: Switch to light mode    
      primary: black
      accent: pink
    - scheme: default
      #toggle:
      # icon: material/toggle-switch-off-outline 
      #  name: Switch to dark mode
      #primary: red
      #accent: purple 

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/CameronCandau
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cameron-candau/

markdown_extensions:
  - toc:
      toc_depth: 0
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
